### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [dphae/bsh#1]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by DarkPark** [comment]
@KTibow thanks for your suggestion.
Can you show some examples?

**Comment by KTibow** [comment]
Here's a [example run](https://github.com/KTibow/ha-blueprint/runs/1520932157?check_suite_focus=true). Expand the "CI" section. Whenever you push to your repo, this will happen:
- It'll format it black + isort for python
  - It'll go ahead and pull it, format it, and amend the changes to the last commit.
- It'll lint it
  - Python: It runs Hassfest (to catch invalid integrations), HACS (to catch invalid HACS integrations), and flake8 (to catch invalid python). It also runs wemake-python-styleguide if you want to follow some of it's suggestions.

**Comment by DarkPark** [comment]
thank you for information
I'll look through custom-components/integration_blueprint and your ha-blueprint repos and assimilate everything useful
